### ISSUE TITLE
lineplot : wrong ylabel ?

### ISSUE THREAD

**Issue by captcha1** [psyplot/psyplot#40]
#### Code Sample, a copy-pastable example if possible

```python
import datetime , psyplot , matplotlib.pyplot as plt

nomads2 ='gefs/gefs%Y%m%d/gefs_pgrb2bp5_all_00z' # GFS Ensemble .5 Degree (Additional Parms) # XXX hack : H hardcoded
f0 = 'gustsfc' # ** surface wind speed (gust) [m/s] , nomads gefs-b
f0 = 'presmsl' # ** mean sea level pressure [pa] # nomads gefs-b

dt0 = datetime.datetime.utcnow() - datetime.timedelta(days=2)
ds0 = psyplot.data.open_dataset(dt0.strftime('https://nomads.ncep.noaa.gov/dods/' + nomads2))
line0 = ds0.psy.plot.lineplot(name = f0,
    ylabel="{desc}",
    title = nomads2.split('/')[0],
    lat = 2*(90 + 38), lon = 2*(360 - 122)
)
print('=== line0 : ', line0)
plt.show()
```
#### Problem description

I expect the ylabel to be "mean sea level pressure", but it's "ensemble member".

Also, it possible to change the scale on the yaxis to be hectopascal (not pascal) ?

Also, the "lat" & "lon" selects are indexes, not degrees.  Is there a way to use degrees ?

Any other tips to make a nice ensemble meteogram are welcome ...

Thanks !

#### Output of ``psyplot -aV``

<details>
psy_maps.plugin:
  requirements:
    cartopy: 0.19.0
  version: 1.4.0
psy_reg.plugin:
  requirements:
    scipy: 1.6.2
    statsmodels: 0.12.2
  version: 1.4.0
psy_simple.plugin:
  version: 1.4.0
psyplot:
  requirements:
    matplotlib: 3.4.3
    numpy: 1.20.1
    pandas: 1.2.5
    python: 3.9.7 (default, Aug 30 2021, 00:00:00)  [GCC 11.2.1 20210728 (Red Hat
      11.2.1-1)]
    xarray: 0.17.0
  version: 1.4.0
psyplot_gui:
  requirements:
    pyqt: 5.15.0
    qt: 5.15.2
    qtconsole: 5.0.3
  version: 1.4.0
</details>

**Comment by Chilipp** [comment]
@captcha1: can this issue be closed?

**Comment by captcha1** [comment]
> @captcha1: can this issue be closed?

yes, thanks
