### ISSUE TITLE
plot2d : KeyError: 0

### ISSUE THREAD

**Issue by captcha1** [psyplot/psyplot#41]
#### Code Sample : 

```python
import datetime , psyplot , matplotlib.pyplot as plt

nomads2 = 'gfs_1p00/gfs%Y%m%d/gfs_1p00_00z' # GFS 1.0 deg # XXX hack : H hardcoded
f0 = 'rhprs' # ** (1000 975 ... 75 50) relative humidity [%]

dt0 = datetime.datetime.utcnow() - datetime.timedelta(days=2)
ds0 = psyplot.data.open_dataset(dt0.strftime('https://nomads.ncep.noaa.gov/dods/' + nomads2))

#p0 = ds0.psy.plot.lineplot(name = f0, lev = 500,
p0 = ds0.psy.plot.plot2d(name = [f0],
    ylabel="{desc}", xlabel = 'time (UTC)',
    title = dt0.strftime(nomads2) + ' ; lat = %(lat)1.2f , lon = %(lon)1.2f',
    lat = 38.0, lon = 360 - 122.0, method="nearest",
)
plt.show()
```
#### Problem description

I want to make a plot2d cross section (xaxis is time, yaxis is level).  Like this : https://fluid.nccs.nasa.gov/gram/meteo/37.7x-122.4

... but the code above says, "KeyError: 0" .  If your swap the plot2d w/ a lineplot, it works, so everything else is OK.

#### Output of ``psyplot -aV``

<details>
psy_maps.plugin:
  requirements:
    cartopy: 0.19.0
  version: 1.4.0
psy_reg.plugin:
  requirements:
    scipy: 1.6.2
    statsmodels: 0.12.2
  version: 1.4.0
psy_simple.plugin:
  version: 1.4.0
psyplot:
  requirements:
    matplotlib: 3.4.3
    numpy: 1.20.1
    pandas: 1.2.5
    python: 3.9.7 (default, Aug 30 2021, 00:00:00)  [GCC 11.2.1 20210728 (Red Hat
      11.2.1-1)]
    xarray: 0.17.0
  version: 1.4.0
psyplot_gui:
  requirements:
    pyqt: 5.15.0
    qt: 5.15.2
    qtconsole: 5.0.3
  version: 1.4.0
</details>

**Comment by Chilipp** [comment]
@captcha1: Can this issue be closed?

**Comment by captcha1** [comment]
> @captcha1: Can this issue be closed?

Yes.  Sorry for my inattention (I've been been trying to learn pyqt / qt-designer well enough to write a GUI weather app).
