### ISSUE TITLE
import error when installing psyplot

### ISSUE THREAD

**Issue by nomanovic** [psyplot/psyplot#44]
#### Code sample and error message

```
Python 3.9.7 | packaged by conda-forge | (default, Sep 29 2021, 19:20:46) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import psyplot.project as psy
WARNING:psyplot.config.rcsetup:Failed to import plugin = psy_simple.plugin!
WARNING:psyplot.config.rcsetup:Failed to import plugin = psy_maps.plugin!
WARNING:psyplot.config.rcsetup:Failed to import plugin = psy_reg.plugin!
WARNING:psyplot:Could not import plugin = psy_simple.plugin
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/onadja/.conda/envs/psyplot/lib/python3.9/site-packages/psyplot/project.py", line 93, in <module>
    _versions = get_versions(requirements=False)
  File "/home/onadja/.conda/envs/psyplot/lib/python3.9/site-packages/psyplot/__init__.py", line 139, in get_versions
    ret[str(ep.module_name)] = mod.get_versions(requirements)
UnboundLocalError: local variable 'mod' referenced before assignment
```

#### Problem description

I tried installing your package according to your very nice documentation. However, when running a simple import (```import psyplot.project as psy```), I ran into a warning and subsequent UnboundLocalError. I installed the package in a clean conda environment with the required dependencies (first: ```conda install -c conda-forge psy-view psy-reg```, then: ```conda install -c conda-forge psyplot```, followed by the code shown above).

**Comment by Chilipp** [comment]
moin @nomanovic! My apologies that you ran into this issue! This is very likely due to an incompatibility of psy-simple with matplotlib 3.5. I am working on this (https://github.com/psyplot/psy-simple/pull/31) but got distracted by other stuff.

In the mean time, it should help to constrain manually to something like `matplotlib<3.5`, i.e.

```
conda install -c conda-forge psy-view psy-reg "matplotlib<3.5"
```

**Comment by nomanovic** [comment]
Oh, yes. Thank you, that fixed it (sorry for not checking that issue).
