### ISSUE TITLE
MapPlot for derived variable looks distorted

### ISSUE THREAD

**Issue by helgehr** [psyplot/psyplot#51]
#### Code Sample, a copy-pastable example if possible

```python
ds = ds.assign(plotable=(lambda x: x)(ds.data))
ds = ds.assign(not_plotable=(lambda x: x+1e-10)(ds.data))
ds.not_plotable.attrs['CDI_grid_type'] = 'unstructured'

psy.plot.mapplot(ds, name='plotable')     # Works completely fine
psy.plot.mapplot(ds, name='not_plotable')     # Plot is distorted
```
#### Problem description

I have some data on a unstructured grid. I want to compute some derived value and plot this but as soon as I change the data just by a tiny bit (adding 10^-10 to it in my example) the resulting plot suddenly looks completely different, distorted, and apparently not attatched to the same grid anymore.
I thought the reason could be that the `CDI_grid_type` attribute was not set for the new (changed) DataArray, so I changed that. I did the same for all other attributes so that `ds.plotable` and `ds.not_plotable` look completely identical on first sight but it does not change the behaviour.

Here is the output of the first mapplot:

<img width="296" alt="Screenshot 2022-03-25 133622" src="https://user-images.githubusercontent.com/38046421/160122044-1c906fdd-fce2-4996-b5c1-eff8335d04cd.png">

Here is the output of the second mapplot:
<img width="314" alt="Screenshot 2022-03-25 133549" src="https://user-images.githubusercontent.com/38046421/160122056-727a2f7b-6b80-4359-99dd-0747fe868b7a.png">

#### Expected Output
I would have expected basically the same Plot for both methods. I am not sure which attribute is missing for `ds.not_plotable` in order to tell psyplot to use the same coordinates as for `ds.plotable`.

A method to achieve the same result which works on the other hand is:
```python
ds = ds.assign(plotable=(lambda x: x)(ds.data))
ds = ds.assign(also_plotable=(lambda x: x)(ds.data))
ds.also_plotable.values += 1e-10

psy.plot.mapplot(ds, name='plotable')     # Works completely fine
psy.plot.mapplot(ds, name='also_plotable')     # Also works
```
But it seems strange to me that the first mentioned method does not work.

#### Output of ``psyplot -aV``

<details>

psy_maps.plugin:
  requirements:
    cartopy: 0.20.2
  version: 1.4.1
psy_reg.plugin:
  requirements:
    scipy: 1.8.0
    statsmodels: 0.13.2
  version: 1.4.0
psy_simple.plugin:
  version: 1.4.1
psyplot:
  requirements:
    matplotlib: 3.5.1
    numpy: 1.21.5
    pandas: 1.4.1
    python: 3.9.12 | packaged by conda-forge | (main, Mar 24 2022, 23:25:59)  [GCC
      10.3.0]
    xarray: 2022.3.0
  version: 1.4.2
psyplot_gui:
  requirements:
    pyqt: 5.12.3
    qt: 5.12.9
    qtconsole: 5.2.2
  version: 1.4.0

</details>

**Comment by Chilipp** [comment]
thanks for reporting @helgehr! Can you share an `ncdump -h` for both variables?

**Comment by helgehr** [comment]
Yes, sure. Do you mean saving the created DataSet as a netcdf file and then sharing the output of `ncdump -h` for that file?

**Comment by Chilipp** [comment]
you can start with the `ncdump` of the original file.

by the way, do you also make sure, that you take the `coordinates` from the `encoding` attribute of `plotable`? For unstructured grids, the `coordinate` attribute is crucial. I.e. you likely need something like

```python
ds["not_plotable"].encoding["coordinates"] = ds["plotable"].encoding["coordinates"]
```

**Comment by helgehr** [comment]
That did the trick, thank you! I thought that some meta information was missing but I did not know that the associated coordinates are in the `encoding` attribute.

**Comment by Chilipp** [comment]
glad to hear that it worked :smiley:
