### ISSUE TITLE
NEW FEATURE: yaml-string for `-fmt` option

### ISSUE THREAD

**Issue by Try2Code** [psyplot/psyplot#59]
#### Summary

let `-fmt` accept yaml-formatted string in addition to filenames

#### Reason

commandline tools should allow as less additional files as possible. Simple format options should not  require the use to write 1- or 2-lines of yaml and store them into a file

#### Examples
```
psyplot input.nc -n ta -pm mapplot -o test.png -fmt "{'cmap' : 'RdBu_r'}"
```

**Comment by Chilipp** [comment]
closed via https://codebase.helmholtz.cloud/psyplot/psyplot/-/issues/59
