### ISSUE TITLE
show_plot_methods() is empty

### ISSUE THREAD

**Issue by RisingPhoelix** [psyplot/psyplot#60]
I am new to psyplot, so maybe I am doing something fundamentally wrong, but I can't plot anything because if I try

`psy.plot.mapplot`

I always get

`AttributeError: 'ProjectPlotter' object has no attribute 'mapplot'`

and if I try

`psy.plot.show_plot_methods()`

I just get no results.

I am running this in a Jupyter Notebook, WSL, Python 3.11 (but I also tries 3.6, 3.7 and 3.9). 

My pip list:
`Package             Version
------------------- -----------------
asttokens           2.4.1
blinker             1.4
Cartopy             0.22.0
certifi             2024.2.2
comm                0.2.2
command-not-found   0.3
contourpy           1.2.0
cryptography        3.4.8
cycler              0.12.1
dbus-python         1.2.18
debugpy             1.8.1
decorator           5.1.1
distro              1.7.0
distro-info         1.1+ubuntu0.2
docrep              0.3.2
executing           2.0.1
fonttools           4.50.0
funcargparse        0.2.5
httplib2            0.20.2
importlib-metadata  4.6.4
install             1.3.5
ipykernel           6.29.3
ipython             8.22.2
jedi                0.19.1
jeepney             0.7.1
joblib              1.3.2
jupyter_client      8.6.1
jupyter_core        5.7.2
keyring             23.5.0
kiwisolver          1.4.5
launchpadlib        1.10.16
lazr.restfulclient  0.14.4
lazr.uri            1.0.6
matplotlib          3.8.3
matplotlib-inline   0.1.6
more-itertools      8.10.0
nest-asyncio        1.6.0
netifaces           0.11.0
numpy               1.26.4
oauthlib            3.2.0
packaging           24.0
pandas              2.2.1
parse               1.20.1
parso               0.8.3
pexpect             4.9.0
pillow              10.2.0
pip                 22.0.2
platformdirs        4.2.0
prompt-toolkit      3.0.43
psutil              5.9.8
psyplot             1.4.3
ptyprocess          0.7.0
pure-eval           0.2.2
Pygments            2.17.2
PyGObject           3.42.1
PyJWT               2.3.0
pyparsing           2.4.7
pyproj              3.6.1
pyshp               2.3.1
python-apt          2.4.0+ubuntu3
python-dateutil     2.9.0.post0
pytz                2024.1
PyYAML              5.4.1
pyzmq               25.1.2
scikit-learn        1.4.1.post1
scipy               1.12.0
seaborn             0.13.2
SecretStorage       3.3.1
setuptools          59.6.0
shapely             2.0.3
six                 1.16.0
stack-data          0.6.3
systemd-python      234
threadpoolctl       3.4.0
tornado             6.4
tqdm                4.66.2
traitlets           5.14.2
tzdata              2024.1
ubuntu-pro-client   8001
ufw                 0.36.1
unattended-upgrades 0.1
UNKNOWN             1.4.3+15.gd603bc0
versioneer          0.29
wadllib             1.3.6
wcwidth             0.2.13
wheel               0.37.1
xarray              2024.2.0
zipp                1.0.0`

**Comment by Chilipp** [comment]
hey @RisingPhoelix. Thanks for reaching out to us here! Psyplot works with plugins, the `psyplot` package itself only contains the core of the framework. The plotmethods are implemented by various plugins, see https://psyplot.github.io/psyplot/installing.html#installation-using-conda and https://psyplot.github.io/psyplot/plugins.html

in your case, the `mapplot` plotmethod ist installed via the `psy-maps` package. so you can add it via `conda install -c conda-forge psy-maps` or `pip install psy-maps` (although `psy-maps` depends on `cartopy`, and `cartopy` is not so easy to install on some operating systems via `pip`. So you are probably better of using `conda`).

**Important:**

there will be new releases of these packages today with many compatibility fixes, especially to the latest version of matplotlib. so you are probably better of trying this tomorrow

**Comment by RisingPhoelix** [comment]
Thank you very much, I will try it out tomorrow!

**Comment by RisingPhoelix** [comment]
Sorry, but I am still having problems. Is there somewhere a list of all the modules that are available? I managed to install `psy-maps`, but now I get `ModuleNotFoundError: No module named 'psyplot.compat'` when I try to plot something. I guess I will have to install something else, but I don't know what.

This is Python 3.11 on Ubuntu (WSL).

Here is the full error message:
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[4], line 7
      5 bounds_arr=np.arange(160,205,5)
      6 # plotting
----> 7 t1_world = psy.plot.mapplot(t1_temp_file, bounds=bounds_arr, name='t', title=f'Temperature Europe ({t1_timestep}H)', ax=axes[0])
      8 t2_world = psy.plot.mapplot(t2_temp_file, bounds=bounds_arr, name='t', title=f'Temperature Europe ({t2_timestep}H)', ax=axes[1])
      9 # style

File ~/.local/lib/python3.11/site-packages/psyplot/project.py:2212, in PlotterInterface.__call__(self, *args, **kwargs)
   2208         if key in valid:
   2209             fmt.setdefault(key, val)
   2211 return self._project_plotter._add_data(
-> 2212     self.plotter_cls,
   2213     *args,
   2214     **dict(
   2215         chain(
   2216             [
   2217                 ("prefer_list", self._prefer_list),
   2218                 ("default_slice", self._default_slice),
   2219             ],
   2220             six.iteritems(self._default_dims),
   2221             six.iteritems(kwargs),
   2222         )
   2223     ),
   2224 )

File ~/.local/lib/python3.11/site-packages/psyplot/project.py:2142, in PlotterInterface.plotter_cls(self)
   2140 if ret is None:
   2141     self._logger.debug("importing %s", self.module)
-> 2142     mod = import_module(self.module)
   2143     plotter = self.plotter_name
   2144     if plotter not in vars(mod):

File /usr/lib/python3.11/importlib/__init__.py:126, in import_module(name, package)
    124             break
    125         level += 1
--> 126 return _bootstrap._gcd_import(name[level:], package, level)

File <frozen importlib._bootstrap>:1206, in _gcd_import(name, package, level)

File <frozen importlib._bootstrap>:1178, in _find_and_load(name, import_)

File <frozen importlib._bootstrap>:1149, in _find_and_load_unlocked(name, import_)

File <frozen importlib._bootstrap>:690, in _load_unlocked(spec)

File <frozen importlib._bootstrap_external>:940, in exec_module(self, module)

File <frozen importlib._bootstrap>:241, in _call_with_frames_removed(f, *args, **kwds)

File ~/.local/lib/python3.11/site-packages/psy_maps/plotters.py:42
     40 import numpy as np
     41 from psyplot import rcParams
---> 42 from psyplot.compat.pycompat import map
     43 from psyplot.docstring import docstrings
     44 from psyplot.data import InteractiveList, _infer_interval_breaks'```

**Comment by Chilipp** [comment]
sorry, yes, my apologies. the new releases for the plugins are not yet there as I am fixing the conda-forge package for psyplot at the moment. they will come by this evening. I will let you know here once everything should work again

**Comment by Chilipp** [comment]
btw, the psyplot packages now moved to the Gitlab of the German Helmholtz Association (https://codebase.helmholtz.cloud/psyplot). They will still recide on GitHub and it is possible to post issues here. The merge requests however will be implemented in GitLab. I will at one point setup a piipeline that pushes contributions from GitHub to GitLab

**Comment by RisingPhoelix** [comment]
Oh, okay. No worries! Take your time

**Comment by RisingPhoelix** [comment]
Thanks, now everything seems to work! :)
